name: 'Haoke CLI Action'
description: 'GitHub Action for Haoke CLI, a command line tool helper for Haoke'
author: 'Haoke'
branding:
  color: 'green'
  icon: 'package'

inputs:
  version:
    description: 'Haoke CLI version'
    default: 'latest'
    required: false
  token:
    description: "GitHub Token used to authenticate against a repository for Git context"
    default: ${{ github.token }}
    required: false

runs:
  using: 'node20'
  main: 'dist/main/main.js'
  post: 'dist/post/main.js'
